Доработал пайплайн, докерфайлы, создал временный docker-compose.

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -3,10 +3,13 @@ name: Service pipeline
 on:
   pull_request:
     branches:
-      - main
-  push:
-    branches:
-      - main
+      - master
+      - dev
+      - 'feature/*'
+    types:
+      - opened
+      - reopened
+      - synchronize
 
 # Список микросервисов
 env:
@@ -14,7 +17,7 @@ env:
 
 jobs:
   check_build_test:
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
     strategy:
       matrix:
         service: ${{ fromJson(env.SERVICES) }} # Преобразование строки в список
@@ -40,8 +43,26 @@ jobs:
       - name: Install dependencies for ${{ matrix.service }}
         run: ./mvnw install -DskipTests=true -f ${{ matrix.service }}/pom.xml
 
+      - name: Run Unit Tests for ${{ matrix.service }}
+        run: ./mvnw test -f ${{ matrix.service }}/pom.xml
+
+      - name: Run Checkstyle for ${{ matrix.service }}
+        run: ./mvnw checkstyle:checkstyle -f ${{ matrix.service }}/pom.xml
+
+      - name: Generate JaCoCo Coverage Report for ${{ matrix.service }}
+        run: ./mvnw org.jacoco:jacoco-maven-plugin:prepare-agent process-classes org.jacoco:jacoco-maven-plugin:report -f ${{ matrix.service }}/pom.xml
+
+      - name: Check JaCoCo Coverage for ${{ matrix.service }}
+        run: |
+          JACOCO_COVERAGE=$(( $(mvn org.jacoco:jacoco-maven-plugin:report -f ${{ matrix.service }}/pom.xml | grep "lines.covered" | awk '{print $3}' | tr -d '%') ))
+          echo "Coverage: $JACOCO_COVERAGE%"
+          if [[ "$JACOCO_COVERAGE" -lt "80" ]]; then
+            echo "Code coverage is less than 80%. Failing the build."
+            exit 1
+          fi
+
   docker_build_push:
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
     needs: check_build_test
     strategy:
       matrix:
@@ -54,7 +75,7 @@ jobs:
       - name: Log in to Docker registry
         uses: docker/login-action@v2
         with:
-          registry: ${{ secrets.DOCKER_REGISTRY }}    docker.io
+          registry: ${{ secrets.DOCKER_REGISTRY }}
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
@@ -64,29 +85,3 @@ jobs:
             --push \
             --platform linux/amd64 \
             -t ${{ secrets.DOCKER_REGISTRY }}/${{ matrix.service }}:${{ github.sha }} ./${{ matrix.service }}
-
-  deploy_to_k8s:
-    runs-on: windows-latest
-    needs: docker_build_push
-    strategy:
-      matrix:
-        service: ${{ fromJson(env.SERVICES) }}
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Set up kubectl
-        uses: azure/setup-kubectl@v3
-        with:
-          version: '1.25.0'
-
-      - name: Configure Kubernetes context
-        env:
-          KUBECONFIG: ${{ secrets.KUBECONFIG }}
-        run: |
-          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
-          export KUBECONFIG=$(pwd)/kubeconfig
-
-      - name: Deploy ${{ matrix.service }} using kubectl
-        run: kubectl apply -f ./k8s/${{ matrix.service }}.yaml
